"""Markdown report renderer."""

from __future__ import annotations

from mm_ready.models import ScanReport, Severity


def render(report: ScanReport) -> str:
    """
    Render a ScanReport into a Markdown-formatted readiness report.

    The output includes a header with database and scan metadata, a summary table of
    check counts by severity, a readiness verdict, findings grouped by severity and
    category (with details and optional remediation), an errors section if present,
    and a footer identifying the generator.

    Parameters:
        report (ScanReport): The scan report to render.

    Returns:
        str: The complete report as a Markdown-formatted string.
    """
    lines = []

    # Header
    lines.append("# MM-Ready: Spock 5 Readiness Report")
    lines.append("")
    lines.append(f"**Database:** {report.database}  ")
    lines.append(f"**Host:** {report.host}:{report.port}  ")
    lines.append(f"**PostgreSQL:** {report.pg_version}  ")
    lines.append(f"**Scan Time:** {report.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}  ")
    lines.append(f"**Target:** Spock {report.spock_target}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    total = report.checks_total
    passed = report.checks_passed
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Checks Run | {total} |")
    lines.append(f"| Checks Passed | {passed} |")
    lines.append(f"| **CRITICAL** | **{report.critical_count}** |")
    lines.append(f"| WARNING | {report.warning_count} |")
    lines.append(f"| CONSIDER | {report.consider_count} |")
    lines.append(f"| INFO | {report.info_count} |")
    lines.append("")

    # Readiness verdict
    if report.critical_count == 0 and report.warning_count == 0:
        lines.append("> **READY** — No critical or warning issues found.")
    elif report.critical_count == 0:
        lines.append(
            "> **CONDITIONALLY READY** — No critical issues, but warnings should be reviewed."
        )
    else:
        lines.append(
            f"> **NOT READY** — {report.critical_count} critical issue(s) must be resolved."
        )
    lines.append("")

    # Findings by severity
    all_findings = report.findings
    for severity in [Severity.CRITICAL, Severity.WARNING, Severity.CONSIDER, Severity.INFO]:
        sev_findings = [f for f in all_findings if f.severity == severity]
        if not sev_findings:
            continue

        lines.append(f"## {severity.value} ({len(sev_findings)})")
        lines.append("")

        # Group by category
        categories = sorted(set(f.category for f in sev_findings))
        for cat in categories:
            cat_findings = [f for f in sev_findings if f.category == cat]
            lines.append(f"### {cat}")
            lines.append("")

            for finding in cat_findings:
                lines.append(f"#### {finding.title}")
                lines.append("")
                if finding.object_name:
                    lines.append(f"**Object:** `{finding.object_name}`  ")
                lines.append(f"**Check:** {finding.check_name}")
                lines.append("")
                lines.append(finding.detail)
                lines.append("")
                if finding.remediation:
                    lines.append(f"**Remediation:** {finding.remediation}")
                    lines.append("")
                lines.append("---")
                lines.append("")

    # Errors
    errors = [r for r in report.results if r.error]
    if errors:
        lines.append("## Errors")
        lines.append("")
        for r in errors:
            lines.append(f"- **{r.category}/{r.check_name}**: {r.error}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by mm-ready v0.1.0*")

    return "\n".join(lines)
